export const ActionType = {
  FETCH_APARTMENTS_START: 'FETCH_APARTMENTS_START',
  FETCH_APARTMENTS_SUCCESS: 'FETCH_APARTMENTS_SUCCESS',
  FETCH_APARTMENTS_FAIL: 'FETCH_APARTMENTS_FAIL',

  UPDATE_APARTMENT: 'UPDATE_APARTMENT',

  INCREASE_APARTMENT_COUNT: 'INCREASE_APARTMENT_COUNT',
  ADD_APARTMENT_TO_FAVORITE: 'ADD_APARTMENT_TO_FAVORITE',

  SORT_APARTMENTS: 'SORTING_APARTMENTS',
  FILTER_APARTMENTS: 'FILTER_APARTMENTS',
  RESET_FILTERS: 'RESET_FILTERS',

  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
};
